# Default values for wireguard-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

kubeRbacProxy:
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    pullPolicy: IfNotPresent
    tag: v0.8.0
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi

manager:
  image:
    repository: ghcr.io/jodevsa/wireguard-operator/operator
    pullPolicy: IfNotPresent
    tag: sha-4189165fa267c75fcce4f1559144486423271a81
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi

wireguard:
  image:
    repository: ghcr.io/jodevsa/wireguard-operator/operator
    tag: sha-4189165fa267c75fcce4f1559144486423271a81

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations:
  kubectl.kubernetes.io/default-container: manager

podSecurityContext:
  runAsNonRoot: true

service:
  type: ClusterIP
  port: 8443


nodeSelector: {}

tolerations: []

affinity: {}

configMap:
  annotations: {}
  data:
    controller_manager_config.yaml: |
      apiVersion: controller-runtime.sigs.k8s.io/v1alpha1
      kind: ControllerManagerConfig
      health:
        healthProbeBindAddress: :8081
      metrics:
        bindAddress: 127.0.0.1:8080
      webhook:
        port: 9443
      leaderElection:
        leaderElect: true
        resourceName: a6d3bffc.example.com

clusterRoles:
  - name: manager
    annotations: {}
    rules:
    - apiGroups:
      - ""
      resources:
      - configmaps
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ""
      resources:
      - nodes
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ""
      resources:
      - secrets
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - ""
      resources:
      - services
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - apps
      resources:
      - deployments
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - apps
      resources:
      - pods
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - vpn.example.com
      resources:
      - wireguardpeers
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - vpn.example.com
      resources:
      - wireguardpeers/finalizers
      verbs:
      - update
    - apiGroups:
      - vpn.example.com
      resources:
      - wireguardpeers/status
      verbs:
      - get
      - patch
      - update
    - apiGroups:
      - vpn.example.com
      resources:
      - wireguards
      verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
    - apiGroups:
      - vpn.example.com
      resources:
      - wireguards/finalizers
      verbs:
      - update
    - apiGroups:
      - vpn.example.com
      resources:
      - wireguards/status
      verbs:
      - get
      - patch
      - update
  - name: proxy
    annotations: {}
    rules:
      - apiGroups:
          - authentication.k8s.io
        resources:
          - tokenreviews
        verbs:
          - create
      - apiGroups:
          - authorization.k8s.io
        resources:
          - subjectaccessreviews
        verbs:
          - create
  - name: metrics-reader
    annotations: {}
    rules:
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - ""
        resources:
          - nodes
        verbs:
          - list
          - watch
      - apiGroups:
          - ""
        resources:
          - pods
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - ""
        resources:
          - secrets
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - ""
        resources:
          - services
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - apps
        resources:
          - deployments
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - apps
        resources:
          - pods
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - vpn.example.com
        resources:
          - wireguardpeers
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - vpn.example.com
        resources:
          - wireguardpeers/finalizers
        verbs:
          - update
      - apiGroups:
          - vpn.example.com
        resources:
          - wireguardpeers/status
        verbs:
          - get
          - patch
          - update
      - apiGroups:
          - vpn.example.com
        resources:
          - wireguards
        verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
      - apiGroups:
          - vpn.example.com
        resources:
          - wireguards/finalizers
        verbs:
          - update
      - apiGroups:
          - vpn.example.com
        resources:
          - wireguards/status
        verbs:
          - get
          - patch
          - update

roles:
  - name: leader-election-role
    annotations: {}
    rules:
      - apiGroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
      - apiGroups:
          - coordination.k8s.io
        resources:
          - leases
        verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
      - apiGroups:
          - ""
        resources:
          - events
        verbs:
          - create
          - patch

wireguardVPN:
  create: false
  spec: {}

wireguardPeers: []