apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "wireguard-operator.fullname" . }}
  labels:
    {{- include "wireguard-operator.labels" . | nindent 4 }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.configMap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
