{{- range $v := .Values.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "wireguard-operator.fullname" $ }}-{{ $v.name}}
  labels:
    {{- include "wireguard-operator.labels" $ | nindent 4 }}
  {{- with $v.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with $v.rules }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
