apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireguard-operator.fullname" . }}
  labels:
    control-plane: controller-manager
    {{- include "wireguard-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    control-plane: controller-manager
    {{- include "wireguard-operator.selectorLabels" . | nindent 4 }}
