{{- range $v := .Values.wireguardPeers }}
---
apiVersion: vpn.example.com/v1alpha1
kind: WireguardPeer
metadata:
  name: $v
  labels:
    {{- include "wireguard-operator.labels" $ | nindent 4 }}
spec:
  wireguardRef: {{ include "wireguard-operator.fullname" $ }}
{{- end }}
